// Generated by CoffeeScript 1.6.3
(function() {
  var CLIController, FileController, SimpleController, async, constants, fs,
    __slice = [].slice;

  fs = require('fs');

  async = require('async');

  constants = require('./constants');

  CLIController = (function() {
    function CLIController(peer) {
      var search;
      process.stdout.write("> ");
      process.stdin.resume();
      process.stdin.setEncoding("utf8");
      search = function(queries, done) {
        peer.search(queries);
        return done();
      };
      process.stdin.on("data", function(data) {
        var done, processData;
        data = data.trim().split('\n');
        processData = function(data, done) {
          var args, command, _ref;
          data = data.trim();
          if (data === "") {
            done();
          }
          _ref = data.split(" "), command = _ref[0], args = 2 <= _ref.length ? __slice.call(_ref, 1) : [];
          command = command.trim();
          switch (command) {
            case constants.HELLO:
              return peer.hello(args, done);
            case constants.PLIST:
              return peer.printKnownPeers(done);
            case constants.DREAM:
              return peer.dream(args, done);
            case constants.EXIT:
              return process.exit(0);
            case constants.NLIST:
              return peer.printNeighbourhood(args, done);
            case constants.JOIN:
              return peer.joinNeighbourhood(done);
            case constants.SEARCH:
              return search(args, done);
            default:
              console.log("unknown command: " + command);
              return done();
          }
        };
        done = function() {
          return process.stdout.write("> ");
        };
        return async.eachSeries(data, processData, done);
      });
    }

    return CLIController;

  })();

  FileController = (function() {
    function FileController(file, peer) {
      fs.readFile(file, {
        encoding: "utf8"
      }, function(err, data) {
        if (err != null) {
          return console.log(err);
        } else {
          return setTimeout(function() {
            var done, processData;
            data = data.trim().split('\n');
            processData = function(data, done) {
              var args, command, _ref;
              data = data.trim();
              if (data === "") {
                done();
              }
              _ref = data.split(" "), command = _ref[0], args = 2 <= _ref.length ? __slice.call(_ref, 1) : [];
              command = command.trim();
              switch (command) {
                case constants.HELLO:
                  return peer.hello(args, done);
                case constants.PLIST:
                  return peer.printKnownPeers(done);
                case constants.DREAM:
                  return peer.dream(args, done);
                case constants.EXIT:
                  return process.exit(0);
                case constants.NLIST:
                  return peer.printNeighbourhood(args, done);
                case constants.JOIN:
                  return peer.joinNeighbourhood(done);
                default:
                  return done();
              }
            };
            done = function() {};
            return async.eachSeries(data, processData, done);
          }, 1000);
        }
      });
    }

    return FileController;

  })();

  SimpleController = (function() {
    function SimpleController(peer) {
      setTimeout(function() {
        return peer.hello(["localhost:8000"], function() {});
      }, 1000);
    }

    return SimpleController;

  })();

  module.exports = {
    CLI: CLIController,
    File: FileController,
    Simple: SimpleController
  };

}).call(this);
