// Generated by CoffeeScript 1.6.3
(function() {
  var FileLogger, fs;

  fs = require('fs');

  FileLogger = (function() {
    function FileLogger(file) {
      this.file = file;
      fs.appendFile(this.file, "###################\n", function() {});
    }

    FileLogger.prototype.log = function(msg) {
      return fs.appendFile(this.file, msg + "\n", function() {});
    };

    return FileLogger;

  })();

  module.exports = FileLogger;

}).call(this);
